jobs:
  include:
  - stage: srpm
    script: bin/srpm.rb
  - stage: arch-x86_64
    script: bin/arch.rb
    arch: amd64
  - stage: arch-ppc64le
    script: bin/arch.rb
    arch: ppc64le
  # - stage: arch-s390x
  #   script: travis_wait bin/arch.rb
  #   arch: s390x
  - stage: finalize
    script: bin/finalize.rb
before_install:
- openssl aes-256-cbc -K $encrypted_ea2bdde4ae67_key -iv $encrypted_ea2bdde4ae67_iv
  -in config/settings.local.yml.enc -out config/settings.local.yml -d
